apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
    - role: controller+worker
      ssh:
        address: 192.168.100.2
        user: k0s
        port: 22
      installFlags:
      - --single
  k0s:
    version: v1.34.2+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: gilfoyle
      spec:
        api:
          address: 192.168.100.2
          port: 6443
          k0sApiPort: 9443
          sans:
            - 192.168.100.1
            - 192.168.100.2
        storage:
          type: kine
        network:
          provider: kuberouter
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          clusterDomain: cluster.gilfoyle
          kubeProxy:
            mode: iptables
        telemetry:
          enabled: false
