# ШАБЛОН. Не коммитить (скрыт .gitignore).
# Порядок:
#   cp secret.yaml secret.enc.yaml
#   sops --encrypt --in-place secret.enc.yaml
#   раскомментировать secret.enc.yaml в kustomization.yaml
#
# ВАЖНО: пароль используется только между ss-server и ss-local ВНУТРИ пода.
# Наружу отдаётся обычный SOCKS5 БЕЗ аутентификации.
apiVersion: v1
kind: Secret
metadata:
    name: ss-zapret2
    namespace: zapret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:/W47rQJfN/Vzlm45f6cBYIKduaa5GHlAinTTs49/VOQ=,iv:yWCcJ6XeBi7rsceTa53atRxctjo4/WsMgT/d4/44X2s=,tag:WINDzF3dEALJ5mFsMKMDmA==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJS2UyWEI2U2NTdzVSZUdT
            N3RlRCtZdDhaeFl0bEMzRDZLbDlhOUZwcWtnCnN3N09BeExER1k4SmhvbHFJc1Az
            UTFGTUhnSEYrN3pqNUZoU1UvNDdTdDgKLS0tIFBCT0QxRTRraG9QN1B3dExaejhK
            T2NhTFBCWVF5MGNNMDl5U1phc1NiWkkKsqRStB8scs1xSJbxU3y+jnMm3+SBVt5k
            YOxBk5mtQQpLeq9vfVOhztFiW6SoWh+cPlZEqqhdXh0kJNtV+xqx2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T21:36:34Z"
    mac: ENC[AES256_GCM,data:CMqU69IMcFCseSKVGt8o1q9vlyulyqVresW+ONtXPMrv3Z0ZAwQPedovgJ/VQMfHe9LTAIE9WiepjCvsOzQZtBIYo/BwUIGqDAkMkXAVLaHYETjbGK9iJhc4fsypwtPsowiETz9+IHngicv5avwTHDlmEzsgomLpzstGG+0Tz0A=,iv:+zfYrX399g/LpLXf18lyCi8B126DX1oYOpCXz4eqqU0=,tag:viiDc5xzn2HYKd3JZq2Yfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
