apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
spec:
  instances: 1
  storage:
    storageClass: local-path-critical
    size: 10Gi
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  bootstrap:
    initdb:
      postInitApplicationSQL:
      # нужен ALTER было ставить для работы встроенных бэкапов. Выполнил руками
      # - ALTER USER immich WITH SUPERUSER;       
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;