apiVersion: v1
kind: Secret
metadata:
    name: mailrise-secret
    namespace: mailrise
type: Opaque
stringData:
    mailrise.conf: ENC[AES256_GCM,data:3Da6xWQTAituF+QmlRsvrgJzLENEAJO7bkDf1zXQ9nKUCNMvRTWoNBbTBUJYAdjDvAvN5MOt0eWcTKiN2nmNVuic+/rUhGaHQcTHpMUsYjzCpoDDYEDSArmVlVx1f/9EGZVCG/TUpgeQJVjhqIR0eQosXr8hmxsR3tY/liZK15FjPKztCpGau0/Vug8NLKXBuYLCdKpH2p729HsQGiOeFGZ7TpA7w8Quc/VzyL9lQ8OE4GQxCcwHq9LcXB2qCsu8Rw==,iv:xTRi7KC51+fuWB+MWDrPefu8aY7FwTbO4fm/AAfcD4I=,tag:aOkv0fc5+EbFZrE/uFDqdA==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMXVVZXRNQ09wcHF2Q01T
            RllmNURibW91Y2tYOFJWeEEvY2lKa21KdG1ZClVTUGtQeW54TDlxR09PanptNkhO
            UG9xTm4zTUhjTFhzcS95d3M0TDRiNmMKLS0tIEpjMzJSTEFhaE5jMDRjdVYwc3d3
            a0FvRXRvVzVaZW1IMVI3UjdIejBEb1kK75janXPjMRW8bIDQh8mbJ6N8YyAIlVzP
            0Oc2cxNI5MfOrOsGY6zgz6RbaGOGXSZxRYO3ut4+6fByslWANStMRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T20:02:01Z"
    mac: ENC[AES256_GCM,data:rgBA7fVwuxmJ3GxG5MDcDosolWrgnfTnCz0CQOW/2Gx9CRXRIUU9qFBUre+SGTPjozgn/9G54APZEw/X+a3vcm1dl9vvjsEFXK1hpWejs4Q3yxEKGIkwapySU0+yn2eauy8GvtCn6EMt4knvYw1k8kkBBCgUcMaH5UgNtQ1nQpY=,iv:KatsgVHGSOyiv0DeSfoZdQ/iYi8JMm0M73DnJKAbSZQ=,tag:Mn3UQ065/H/koLU7u5p03Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
