apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
  - secret.enc.yaml
  - provider-config.yaml
  - vps-deployments/common-bootstrap.yaml
#  - vps-deployments/ygg-node.yaml
