apiVersion: ansible.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: ansible-vps-config
spec:
  credentials:
    - source: Secret
      filename: /tmp/id_rsa
      secretRef:
        name: vps-secrets-and-inventory
        namespace: crossplane-system
        key: id_rsa
