apiVersion: ansible.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: ansible-vps-config
spec:
  credentials:
    - source: Secret
      filename: id_rsa
      secretRef:
        name: vps-secrets-and-inventory
        namespace: crossplane-system
        key: id_rsa
    - source: Secret
      filename: ygg_socks_pass
      secretRef:
        name: vps-secrets-and-inventory
        namespace: crossplane-system
        key: ygg_socks_pass
    - source: Secret
      filename: ygg_private_key
      secretRef:
        name: vps-secrets-and-inventory
        namespace: crossplane-system
        key: ygg_private_key
    - source: Secret
      filename: telemt_user_sprinthost
      secretRef:
        name: vps-secrets-and-inventory
        namespace: crossplane-system
        key: telemt_user_sprinthost
    - source: Secret
      filename: telemt_pass_sprinthost
      secretRef:
        name: vps-secrets-and-inventory
        namespace: crossplane-system
        key: telemt_pass_sprinthost
