apiVersion: v1
kind: Secret
metadata:
    name: vps-secrets-and-inventory
    namespace: crossplane-system
type: Opaque
stringData:
    ygg_socks_pass: ENC[AES256_GCM,data:ZIKChN/cDuAYE25NWq+5VGNYzJ0MdD8C44/yAKsRAFEAsP7WUMqSFTE=,iv:Ii1TGJkc23N6sGkfQU2HEPTT8VoJY89OI37vq2QS8m4=,tag:+Pt2n7X5TXTD2+AwP8otkA==,type:str]
    ygg_private_key: ENC[AES256_GCM,data:2UQX2Nt36dTwbxTFUeA9pRyPZIiREEe0ydUr7o+9w3RsUJ2P0ePW4cfluGUPsRAXJu2Y44mhiLnpXLp1YNcJ2qFl2g09HMN+Hx4O4xMeZaARRcpl/Nf/bgTrcSiD95mUTO7/3+PhNk/6q56K26F3+LbEI/d784m4Y9xEymny22A=,iv:mDIsLRHdmrMjn1kBINP1GHkWD/93793X+h4vo1Yrg84=,tag:+ux3o5WePU1OIeQnPL2Gdg==,type:str]
    id_rsa: ENC[AES256_GCM,data:geegI5uOB0VmzLU7JscatNflP20B7gAtB1HUfAreJWVjYHCq319D4bdPrJXnkIdJXs7Sxbqgj3y+ShA9+BFVlIkZ0A1QfEou2d58D6JX2NXY6FB2XCS571k8GwgTEW/4OLPmslx8HDDCgSfmuQZsTqMZF45qlg+1OGWjzv4IOfhEiGifUz9jOPmN0IQ0Q1ebrB8SuufmLHsD4WG1o+t9x42dWouZWRacpkm7iQRKoQsK/T5SlVdA64Pb950nx584JaczzMuOjmBD7eADG8Oj8X2PVauY7HDLiLkjOxRHDCSXrOnN3PVkCRIAXITR0Dq1xpTSHSHeiOuKDfzSjAtcxr485frckvZD3Z1UveEP9tFZ6qAaTeu1ycGW9g0Wd21z49wG4bfxAlrYZZlun/hYGC+qtjPLzh9B2RH0Sh4jLOC2srZjO8i3dEoMY99vKwlk9+DffqsfwJismC2+JPDMvAHA1Rt4P4LkXHaFZVvT8LSwbSVkszVpN3anG9Hp8QSiG8RXJ343mH8AdNkY1OZmLAgVEgjlq7RtP14Q,iv:AnrEuolhXMV5ameh6RsX/Dhbw45LR8bRMvptPx2oNVI=,tag:170KRCseKpgFWJwawHg1kw==,type:str]
    hosts.ini: ENC[AES256_GCM,data:Tf5AK+nNom9ziplSuIaa2C9x5bh/Sr1f0XRI6QKu2m7ToBEbr8HoPe4fDjJCcnp2fQlw4GW+0P3vgDizAgXaHPOjU6Mng4I79ZguoN9aHIVGzAxj/jB2vPi1FJ5k2IKLqfn9MqQRzqMns3ovzGhGDcYWAzl21z8R5h+uTm9tqQ650n4rxOC0b+wGEy6rpjyJTTl+PTiEwE4JY2aLBs6e4gUxbSahqWWuoIPlh5t5PjWx+bnw8RNIzjAQUi9f1sdDNANGqglBIcj1iWDiqFWm4fI5UUgWlJvj73dCw56o7h2nRkpE53cfRw1sJDyaicUvV2wm9uw=,iv:m0RFgfX0fZh1m0QnJSI5MwmAYt2wdo2XGVcMP6nG/Ao=,tag:ksdtKjQIa/7Kz6pxUZlLMw==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaXlRV1VWWTE0clZmQXN5
            UTNZNjAxRjZKZFVrNjZCUUZoOXBFNkVodmcwCmRkY3B5MjJBU0o0ODhhWG5oRUZk
            QkI2eWw0WVpuTGdIK1pvL2VVSHRUaFkKLS0tIFZQeHVtSENzdWdjOTVkNGNvWE5v
            UXZQT0pBKy8wYW5HNFJGTWt3R2ZuT3MKLowB4vqfNWzZiH6Cq/uQ0FXFAGuynNiK
            Mt16PRio6lm7EUb/ROO17rlfCyy+sBuOiJ9+AjsyO4MTQf3YUJ1W5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T21:29:00Z"
    mac: ENC[AES256_GCM,data:4npat3VEz12BZD7a7XRppZA31tNz8yd2oJ2ptLE/fAq1fcIwL+wZYDHXpa7yYnZWgWHvCXP9s4KdSyUP3FbWzzNzwSTTJVAz2SY4IvglxLrEv8CTMgNlhTISeWfs+BT5+ujMQe2t7DU/zPo1D25yakMJp6h7h0LCTl1GBILlbVU=,iv:eYkOG/ILckEJ+sJ/bZ7pZ6nv51KgBJNZCaLqwP3e0Wg=,tag:n65LxW76Kd64HJMz/tR5CQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
