apiVersion: v1
kind: Secret
metadata:
    name: vps-secrets-and-inventory
    namespace: crossplane-system
type: Opaque
stringData:
    ygg_socks_pass: ENC[AES256_GCM,data:ZIKChN/cDuAYE25NWq+5VGNYzJ0MdD8C44/yAKsRAFEAsP7WUMqSFTE=,iv:Ii1TGJkc23N6sGkfQU2HEPTT8VoJY89OI37vq2QS8m4=,tag:+Pt2n7X5TXTD2+AwP8otkA==,type:str]
    ygg_private_key: ENC[AES256_GCM,data:2UQX2Nt36dTwbxTFUeA9pRyPZIiREEe0ydUr7o+9w3RsUJ2P0ePW4cfluGUPsRAXJu2Y44mhiLnpXLp1YNcJ2qFl2g09HMN+Hx4O4xMeZaARRcpl/Nf/bgTrcSiD95mUTO7/3+PhNk/6q56K26F3+LbEI/d784m4Y9xEymny22A=,iv:mDIsLRHdmrMjn1kBINP1GHkWD/93793X+h4vo1Yrg84=,tag:+ux3o5WePU1OIeQnPL2Gdg==,type:str]
    id_rsa: ENC[AES256_GCM,data:geegI5uOB0VmzLU7JscatNflP20B7gAtB1HUfAreJWVjYHCq319D4bdPrJXnkIdJXs7Sxbqgj3y+ShA9+BFVlIkZ0A1QfEou2d58D6JX2NXY6FB2XCS571k8GwgTEW/4OLPmslx8HDDCgSfmuQZsTqMZF45qlg+1OGWjzv4IOfhEiGifUz9jOPmN0IQ0Q1ebrB8SuufmLHsD4WG1o+t9x42dWouZWRacpkm7iQRKoQsK/T5SlVdA64Pb950nx584JaczzMuOjmBD7eADG8Oj8X2PVauY7HDLiLkjOxRHDCSXrOnN3PVkCRIAXITR0Dq1xpTSHSHeiOuKDfzSjAtcxr485frckvZD3Z1UveEP9tFZ6qAaTeu1ycGW9g0Wd21z49wG4bfxAlrYZZlun/hYGC+qtjPLzh9B2RH0Sh4jLOC2srZjO8i3dEoMY99vKwlk9+DffqsfwJismC2+JPDMvAHA1Rt4P4LkXHaFZVvT8LSwbSVkszVpN3anG9Hp8QSiG8RXJ343mH8AdNkY1OZmLAgVEgjlq7RtP14Q,iv:AnrEuolhXMV5ameh6RsX/Dhbw45LR8bRMvptPx2oNVI=,tag:170KRCseKpgFWJwawHg1kw==,type:str]
    hosts.ini: ENC[AES256_GCM,data:R5dv9PEW7xlXlCQFifCWqJAcbBeWgYrjrz3OYJcNGT0Y1P20GVWXgrBYl0GxN2zL1BaWmjHLel1FjwlBuwWtBDkXYLfVgH1ZxC60fYeoEGlbHwSfeEHFU9EDvVD6sA9uSMXyQGov0Z2Fgr9LFgDVW5HuENy2tJWyXOH0na8q/ljeE05c82oMjwpej7Y4pYhR/aGplE+c2sFG413Dcu3+EhSQ6bOyFO0YHPTZSTkcKzc2ZJmNE48zchc89DwszawteF04+rkhaDTXmdHghyvHQJ0mHFmN+4UjYM6pp+O9fMo=,iv:oCJwBtmADKjisirYYV7JVrMnaH60wXW/HarUEIQ7Pbo=,tag:e7uEyLllUbhwDp4Qe4T2rg==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaXlRV1VWWTE0clZmQXN5
            UTNZNjAxRjZKZFVrNjZCUUZoOXBFNkVodmcwCmRkY3B5MjJBU0o0ODhhWG5oRUZk
            QkI2eWw0WVpuTGdIK1pvL2VVSHRUaFkKLS0tIFZQeHVtSENzdWdjOTVkNGNvWE5v
            UXZQT0pBKy8wYW5HNFJGTWt3R2ZuT3MKLowB4vqfNWzZiH6Cq/uQ0FXFAGuynNiK
            Mt16PRio6lm7EUb/ROO17rlfCyy+sBuOiJ9+AjsyO4MTQf3YUJ1W5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T22:30:38Z"
    mac: ENC[AES256_GCM,data:vtSB+ILW9SouYhhWtheaRdQMZvdZpmCls+nytZ0rmVkegnnA9avbUJUrmYBTpAeEJpFP5EEAg4+kMnxhR6S78JU3K/tTQR3Q2g+0Pmw9PDLEcCqwAzOdBrB94ZWLgKf13sPYftYkbV73TjrYUYHJ1WJq+1S4ZrBr4He9/KPKRVk=,iv:nnXeseXaFr8k4TppmY57WcMpRhzu9Jbt4vRp4celcBQ=,tag:LSjZHOPKdmgfa+jiPDH/CA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
