apiVersion: v1
kind: Secret
metadata:
    name: vps-secrets-and-inventory
    namespace: crossplane-system
type: Opaque
stringData:
    ygg_socks_pass: ENC[AES256_GCM,data:ZIKChN/cDuAYE25NWq+5VGNYzJ0MdD8C44/yAKsRAFEAsP7WUMqSFTE=,iv:Ii1TGJkc23N6sGkfQU2HEPTT8VoJY89OI37vq2QS8m4=,tag:+Pt2n7X5TXTD2+AwP8otkA==,type:str]
    ygg_private_key: ENC[AES256_GCM,data:2UQX2Nt36dTwbxTFUeA9pRyPZIiREEe0ydUr7o+9w3RsUJ2P0ePW4cfluGUPsRAXJu2Y44mhiLnpXLp1YNcJ2qFl2g09HMN+Hx4O4xMeZaARRcpl/Nf/bgTrcSiD95mUTO7/3+PhNk/6q56K26F3+LbEI/d784m4Y9xEymny22A=,iv:mDIsLRHdmrMjn1kBINP1GHkWD/93793X+h4vo1Yrg84=,tag:+ux3o5WePU1OIeQnPL2Gdg==,type:str]
    id_rsa: ENC[AES256_GCM,data:geegI5uOB0VmzLU7JscatNflP20B7gAtB1HUfAreJWVjYHCq319D4bdPrJXnkIdJXs7Sxbqgj3y+ShA9+BFVlIkZ0A1QfEou2d58D6JX2NXY6FB2XCS571k8GwgTEW/4OLPmslx8HDDCgSfmuQZsTqMZF45qlg+1OGWjzv4IOfhEiGifUz9jOPmN0IQ0Q1ebrB8SuufmLHsD4WG1o+t9x42dWouZWRacpkm7iQRKoQsK/T5SlVdA64Pb950nx584JaczzMuOjmBD7eADG8Oj8X2PVauY7HDLiLkjOxRHDCSXrOnN3PVkCRIAXITR0Dq1xpTSHSHeiOuKDfzSjAtcxr485frckvZD3Z1UveEP9tFZ6qAaTeu1ycGW9g0Wd21z49wG4bfxAlrYZZlun/hYGC+qtjPLzh9B2RH0Sh4jLOC2srZjO8i3dEoMY99vKwlk9+DffqsfwJismC2+JPDMvAHA1Rt4P4LkXHaFZVvT8LSwbSVkszVpN3anG9Hp8QSiG8RXJ343mH8AdNkY1OZmLAgVEgjlq7RtP14Q,iv:AnrEuolhXMV5ameh6RsX/Dhbw45LR8bRMvptPx2oNVI=,tag:170KRCseKpgFWJwawHg1kw==,type:str]
    hosts.ini: ENC[AES256_GCM,data:vu7vEG51au+p2RIwZb9ehPH83HvpDLayE493O+rlwbop4bO74YKv4Ku1dPFnwPVCNXPh1uDG5HkEg9cEdpG2Wwj7eIeGqBAa3kwSBSaOiJDhzgTaWDmGhcMJI9XleOcpr+GF3Rt0NmSAHU18tz5vOx9TyoAdapruPnL7YtN8f2pscNpzPudwxZhmMBLafC52YJrwK7udxqJgvcuv6ySBuGTl2wigGAImeFIBsi4ViyxxA/3WfdHtGn3trqucUrSdP/hk2ifSUdTt8sl/BTrOZZ32DL/Y4XQmCRLKF44w9PP6R+HmO05H3IM=,iv:bH6kB6DXGViJ/WM+eKmxBk3tGMUlRShTVw5TyFdeBek=,tag:7jM+7jgkipvHaCLTEakuGQ==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaXlRV1VWWTE0clZmQXN5
            UTNZNjAxRjZKZFVrNjZCUUZoOXBFNkVodmcwCmRkY3B5MjJBU0o0ODhhWG5oRUZk
            QkI2eWw0WVpuTGdIK1pvL2VVSHRUaFkKLS0tIFZQeHVtSENzdWdjOTVkNGNvWE5v
            UXZQT0pBKy8wYW5HNFJGTWt3R2ZuT3MKLowB4vqfNWzZiH6Cq/uQ0FXFAGuynNiK
            Mt16PRio6lm7EUb/ROO17rlfCyy+sBuOiJ9+AjsyO4MTQf3YUJ1W5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T22:28:33Z"
    mac: ENC[AES256_GCM,data:s09iIoQdzKIbfDzPsPeclMK0QQSPE+UKs2iSvdrsIieG6i+rGAu1AUbaNnGqt7CJ1eSEyy4M3jcgB9qGSu6fOQpSbUObJJSUkF7eH8ri5gNWBdoE6AKffn3lJ1lIWb/RJK7nvTvQutBbcYpN1lKXKXUpPuJvhCT6ivXIRQwG0rg=,iv:+P12zIk7VV3JJrsmejkP+z17KN14JgFkenDnW7f9mFk=,tag:eqWOTyl0GzorqZQJHayNEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
