apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  releaseName: crossplane
  chart:
    spec:
      chart: ./01-flux/gilfoyle/apps/crossplane/charts/crossplane
      version: "v2.3.1"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 60m
  interval: 15m
  timeout: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    provider:
      packages:
        - mirror.gcr.io/crossplane-contrib/provider-ansible:v0.8.0
