apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  chart: ./01-flux/gilfoyle/apps/crossplane/charts/crossplane
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 60m
  version: "v2.3.1"
