apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- ./grafana
#- ./victoria-logs
- ./local-path-storage
#- ./envoy-gateway
#- ./metallb
- ./cert-manager
- ./crossplane
- ./crossplane-vps
- ./dynamic-dns
- ./cloudnative-pg
- ./immich
- ./mailrise
- ./pocketid
- ./backup-critical-data
- ./immichman
- ./homebox
- ./haproxy-ingress
- ./hellpot
#- ./ntfy
- ./ygg-gateway
- ./databag
- ./xmp-viz
- ./zot
- ./reflector
- ./coroot-operator
- ./coroot
