apiVersion: v1
kind: Secret
metadata:
    name: zot-registry-secret
    namespace: reflector
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: xpm-viz
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:VoSl62wgJB6yvqK8MrshXPKS1Gl+4UvqbanPAPZCnyTUd1g+uOI3ArtRo/UgPLIJwAEAn/QKRZSy+vittGZYFAJFaPDtOQrBpYDeLHcQ59uwaFJsPD7LnUrHuMBXVtqirw8Wv2Otu601r0X4nSyxij79cEfAwazuPwM0,iv:th/+Y0psATt/EwSeBgTxcN824HxRVJD+BByJ88H3+is=,tag:cqnYBQfeSO258pL5vCcXsw==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvY0J5a3JDV3VaRUFJb3BS
            WkRDQXIwMUJyV2R1UmtIaXFXNUlqSTB4ZkQwCjltcHh3dGZhWWtRRmo5ZDR4TldE
            M0hSZUZ0VnVDNFRSTzV3czd4bWUxNUEKLS0tIHpTNGJrTkUybXgwMWF0NzgrUEJi
            M2g2ZElvSW5vZ2RtSmFmMVpOTklaZ1UKaz3FKq+Dt28Ur4HIlCoUQRSLx0OPSW4W
            v+oS6Ft7mim4IFNXxG+r0WQcH+oC78kWMFstr0b/QiE4udw4+rQBHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T21:50:29Z"
    mac: ENC[AES256_GCM,data:0WVhoqurra82d6bEJQq7F2zPKKGnxvXvWWnLjCQA1l0RM9B6f3iNUUFD6p37bFOHMFckmgIkJTA7kFs3QvirgnulLxF8G6K9YrjSVOx+702xhyb2ni2EI+hLtnhazGh7Oea+CUylRcuh5xibQjZ4796HvWT2N/l2NUNDX2WZ8vY=,iv:1GKkEs1dEKkK6WKF/XrX9AseD9Euhhf1IBPMKlIb3n4=,tag:qhsxkNPT2YBCdf0pVKTfiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
