apiVersion: v1
kind: Secret
metadata:
    name: zot-registry-secret
    namespace: reflector
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: xpm-viz
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:AB7WMgjN2pjLlul2T/0VGpIe7Y9c/XxJsIJv8samu/M78O9GZNmsEui4rpi81Eqr0m0/OCF1RvLtmTkqdk2qkRvb2/1csvkHv6cw/a0KugLTwDsJ502KYQ==,iv:fO6vGUSO4MoO3Vh/0116FGkF2pEwAJlsMcMxB/ZQRdA=,tag:YxnmWKBURI14VAB7jZWsoA==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdlRUamNOVjhVbnZqTnNC
            andINW1UQ3hjWjdyV0xCcEROQXowOWE0QlQwClhDNTZFMXEwTUgyZWxFa2R3Yzlm
            NlB1Zzhtd2FEMUZkeW1RQ3k5S2pOMU0KLS0tIG1VNVcxVVdhY1piZXFvVUIxUDFv
            bHlPRXJJTXQ1ZmtuOEE3R3pKRlpmWFkKUB/KSAz0xpbMqNg1RZvtmPG4mtSGUHsi
            mu+bsUDK7y/Etx5Qsn/dZQnNAvTCzFUT/En+n7BTRyGJdLtd++3d5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T21:58:22Z"
    mac: ENC[AES256_GCM,data:EqC1KPKU4Yvsq8JfIPsIvxeZ6T31zmYQHtmg7Cpg9wdx9EQuE+MiDEV5SGQr3z8VYm54MHKQadNTLl9CWW1nq4XyeUtNBH/XSSd8G1WnCqnB5bU6GDxyUvrQSqdSTQ+/zIYzjClmcW8aZAKLAfcz/BrIr6ncT77ZM/qYG6bJvwI=,iv:hIfx6MEeDnlWRhD1GxMnIHmrS715RdMkoZ86GkkWBJI=,tag:v2zY1AWmhHxCpmRUkKCHKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
