apiVersion: v1
kind: Secret
metadata:
    name: zot-registry-secret
    namespace: reflector
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: xpm-viz
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:YNG6p91aXl/MtdLfq1qcY+k7pEZjAdpPqcr5uZo1flNapLY8Z2scASeAdOcwifkMRkN0GWW0m9NUMERDfUZcxFPK70eHnCz9LFQ0aG5GRincqxFin8SEow==,iv:vicYvz+OGYRcsq7lejgph0IXRGAuhYhIjQUC1dKYfvU=,tag:foRbDw+qVn+xxEAQp4yHDw==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpV2lTUVpReklwNkx0YlND
            Q2Q0MEhWaE0xUklIZldmeHVhZVhyZGdpSFRjCmNJc0dwSmJNSVRpMTIyRVVOUC9m
            aWF5Y3AvUHlhSkJ1dEJSMmVJajY3QmsKLS0tIEZoelBSTHVrdFcwaVBPaHlKb0xk
            THJSVXpBNG9Obk1YK3ZSK1VOYnlJOXMKPr7aYW2zdkzS/sOzoWV6T1qxQdN2VgxJ
            WI2QKa89MwbBKsnc4CYpHw9l6pWnL/EUQ/GxiExClHvlor7Cr/LPfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T21:54:12Z"
    mac: ENC[AES256_GCM,data:xk02tazp7M6wgT9OrNq+afBxCbAYLp+/4ugkzzn7ZsuUILkGAdstHm/V56302mdOyEzOpC005rQaHrMicvyVzmeCaATwRvSx7d0AumFKhw+9maYsFkH+qE3jwKJo+UC24BtsUxGGYMhm0JTFxt3pTBYXEJfoU7qc1sUjrbmlLnc=,iv:w46ctJ11WOz5uuj/OLNUSDTRjvfVXjzIZcaQYLt5PH8=,tag:0ofGbXESVh1EqADkPkVTdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
