apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: coroot
type: Opaque
stringData:
    #ENC[AES256_GCM,data:gk2+sMYdT8wJ5/Io1YdoIieaW/vN27lAVOObzw8=,iv:knVznpRIZaQtow6MkB2CSy5biLM3gAQo5xQ5/B9+Jhg=,tag:dUS3kFJDf5MR9nMdxc1ONA==,type:comment]
    client-id: ENC[AES256_GCM,data:fsPR03bbdCkDrp445tXOs9Gr+TjlP453tVB4JSZ7zaai7dGn,iv:K+mOdWYdiVu2+q25ObquUgoq9SoCFeAqNnPoVmOAbx8=,tag:FZVNR87s9negJi9QVwktZw==,type:str]
    #ENC[AES256_GCM,data:nwdptSMXR07pZyk3n23ypsq4V2Dt/h99nfmzG9ojXYyp,iv:3xtL319/se6ZNBwOkzV+/CQbHEnXrdPFRdbTRyNSDdw=,tag:TL+R3ZWXBpVIWMDf7jASQg==,type:comment]
    client-secret: ENC[AES256_GCM,data:DvHP4gAUnvmWr7VjBudUjgPG5yhEKhVP/snlK5JgHAc=,iv:GVJrczkcrLHbkiv0kzKUKKJnbwI9volZuBMNECgrDkE=,tag:rQKoAI25vuAO895huton4Q==,type:str]
    #ENC[AES256_GCM,data:Jxeni0ZDNLXHwRfaR/8nXj9WzE69ZTI1ZuhUeXHfbZQIug==,iv:IU/+AU7wdjhtshLLBJCuu9BMZnw70sG369liYaJLKy4=,tag:AJHwme5ygXKFqbnu/ajXVw==,type:comment]
    cookie-secret: ENC[AES256_GCM,data:l2Z+tCvpejoVHTtSyWNOHMRuTOlSPiRogU3v68qyHMnNkWLxlnvJZB3GEzw=,iv:Z3y332jgM2k3venpz6AfAC2zDzJ46WGnv38/eOx+FeE=,tag:jlwX7Hv7NdZhgz+pP02Epg==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VmlLaDRVR1Y1T1FUbFhk
            MXdrYmtFS1F2c20vaGcwU01wZzlmcHRaWWdjCnFGWDlISG51cXhwMXpYaVJyeFo5
            VmVCdWIzRjhEM0l5MmJGZWI5TTFhdFkKLS0tIG9QL1kvc0toSnlsWlFwNDk5QWlO
            NjRFR0hwMUtCazdBLzRmTUdXZzMrcDAKKqkfJ4JgfPytdHW2+WDIzvydJYZBsHEZ
            Xo7aBxbFMG4VjW2T3sVYKIhgh4zTlJhHEPQ78jTdUgtmHYa3kDDHVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-10T21:29:27Z"
    mac: ENC[AES256_GCM,data:eNKDIGNfItxcc8i0QU/Ag6xC1pDqhDjh37Bz1kWaketvMGUplZwsL8Y1ALBw+k/O/yD7uwYvrFsWDWqm26bwPUZSDyrGUKiyBRVyuyE2gH78u6iY2fLB/sk0kLwssN0s/t3D1bRD4FYOQKNrFax7izORzHR0xP8sFoT0ANriLOQ=,iv:0PkuRsiWye2Th0jHYCDbINYHyt+Li5tLojteZN2BM0M=,tag:YVIOLnjRVOH9lJ0Z9s96Vw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
