apiVersion: v1
kind: ConfigMap
metadata:
  name: global-autorestic-config
  namespace: backup-critical-data
data:
  ssh-config: |
    Host *
      StrictHostKeyChecking no
      UserKnownHostsFile /dev/null

  .autorestic.yml: |
    version: 2
    
    locations:
      immich:
        from: /mnt/pvc-f44fd884-aa55-4d12-9081-c2d586b96a63_immich_immich-library-pvc
        to: jipoksftp
        options:
          backup:
            host: "k8s-immich-worker" 
            exclude:
              - "thumbs/"
              - "encoded-video/"
          forget:
            keep-last: 7
            keep-daily: 7
            keep-weekly: 4
            keep-monthly: 6
            keep-yearly: 3
            prune: true
        hooks:
          failure:
            - >-
              curl -s -X POST -x "socks5h://ygg-gateway:1080" 
              -d "chat_id=$TELEGRAM_CHAT_ID&text=❌ <b>Backup Failed!</b>%0A%0ALocation: $AUTORESTIC_LOCATION%0ACheck logs for details.&parse_mode=HTML" 
              "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage"

          success:
            - >-
              curl -s -X POST -x "socks5h://ygg-gateway:1080" 
              -d "chat_id=$TELEGRAM_CHAT_ID&text=✅ <b>Backup Successful</b>%0A%0A📁 Location: $AUTORESTIC_LOCATION%0A📸 Snapshot: $AUTORESTIC_SNAPSHOT_ID_0%0A📊 Added Size: $AUTORESTIC_ADDED_SIZE_0%0A⏱ Duration: $AUTORESTIC_PROCESSED_DURATION_0&parse_mode=HTML" 
              "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage"

      homebox:
        from: /mnt/pvc-35f1d939-e914-452f-8ab1-8a751cd066c3_homebox_homebox-data
        to: jipoksftp
        options:
          backup:
            host: "k8s-homebox-worker" 
          forget:
            keep-last: 7
            keep-daily: 7
            keep-weekly: 4
            keep-monthly: 6
            keep-yearly: 3
            prune: true
        hooks:
          failure:
            - >-
              curl -s -X POST -x "socks5h://ygg-gateway:1080" 
              -d "chat_id=$TELEGRAM_CHAT_ID&text=❌ <b>Backup Failed!</b>%0A%0ALocation: $AUTORESTIC_LOCATION%0ACheck logs for details.&parse_mode=HTML" 
              "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage"

          success:
            - >-
              curl -s -X POST -x "socks5h://ygg-gateway:1080" 
              -d "chat_id=$TELEGRAM_CHAT_ID&text=✅ <b>Backup Successful</b>%0A%0A📁 Location: $AUTORESTIC_LOCATION%0A📸 Snapshot: $AUTORESTIC_SNAPSHOT_ID_0%0A📊 Added Size: $AUTORESTIC_ADDED_SIZE_0%0A⏱ Duration: $AUTORESTIC_PROCESSED_DURATION_0&parse_mode=HTML" 
              "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage"

    backends:
      jipoksftp:
        type: sftp
        path: serj@ateam.undo.it:/home/serj/hdd/k8s-backups
