apiVersion: v1
kind: Secret
metadata:
    name: homebox-oidc
    namespace: homebox
    labels:
        app: homebox
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:3NrP+J7A3cTKt/KKmlrr4ROHNd4ZX3me4btuoSY2fRjsaLyz,iv:yRdCEmwUKWKcdJU/FAusM/1YuhcxdzmRNaL3LZzkme0=,tag:C3z2p6mIxxb07vzUbOCMRw==,type:str]
    client-secret: ENC[AES256_GCM,data:O8+QvaYLR3gLgn0dtife1x8fWJxKYfa38TcXo6JbW84=,iv:Adeo6MixOYpR71SlaFLTrs51jcxPuAD0qMau3fLEpEI=,tag:peuOw2258PjtbOKp15iRQQ==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dFZyTE5GVVJCSytwalZs
            SFN3dUVZK2hmRm0vOVdCSW1OZThCWExqaWhnCnJBUVg4MEhvQnpmdzlnM1pBMWhO
            LzRKV21uNFFEWEYzNUo2UjVQRzhaL0kKLS0tIC9KSWM4QThNb0I5Z3ArL0ZYRlBU
            T2orTWlTL1o2WW8rcHNRS3RORjBpaGcKM/0JsY5r929UwJWwT34nDEFVr6vZS2WG
            C+E8AQwDl0zfI2AMu28q+YC8/N6kTaLwD51CxDI+gwU5ihdYNQNCPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T20:34:44Z"
    mac: ENC[AES256_GCM,data:BWenZB5lxNQHn9w6o6FQeaPZ7WWSdmRfgMdBvPgvyIPiMq9tNF55pE4Zu/xUw1oIGZVnKbp9ns1EGJ3Fnei4Sg+g918t864RbIyjZyjnDz6I7fwLx5vF9xsQZLjcdWB+gAU44KC/3ZX6wFsNqIBM/ED9sCXCV80eugL9zkjXZ/8=,iv:j4UIqj5xQu3ChmFjMpY7u9DjfLB7Iqq6sDBZ27rsPQA=,tag:0WGdq0yrMW2WywDxVlPivQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
