apiVersion: v1
kind: Secret
metadata:
    name: ntfy-server-secret
    namespace: ntfy
type: Opaque
stringData:
    server.yml: ENC[AES256_GCM,data:nfhpycK6IpnUPslok/I9TNGjMDGwBZz/EqO2aWntqH8mY6xSHi+KSs3uBv3qw/yW8331WnaUWCUw+5HJGq9f74mG8181EUUEgCWEdHewJ9z5IzxiCIXfDZZk+nTUFloVYEAEU1bnvbazkOnxdkOiUDJXXMe78s3I1Dg5g9Ml1MmCUYgq3uNuJETY3nys/p40NCj1/Tid3boMT7E7wU3GJqiBetTK9it5VVXzkbwJXY0VlI2Q/Uv4IiqUazSe4F82Ah5/vivmb4C98ngEmROtIX2VoGYR7vpeQZQs/R4YQvFFaCfwG+YKJ2j6wRyLmVts+AGhMQBQvOcozuppKZo5tPg9hdGmxkLiyguvsPfFiOMXlzS5eiudfe4c/vGvOPDD5N8W1xMTXoFVj37NOOsU2sxsa+Pnmo0vuVY6kvpBovxbvUxMejBu+Rd1vOc0j0y6sssXTfc/7CZxddY/cpz2To8gKDXYeSipDv6Whc0EQ4lJamZuCiTosE1s9Zyl86LLcYlPwW1/l5iQxb0Qr2kh1hJt9RaAhtJKCRrLIgaTSyEU8KEG2wPAO6HG4J6QG9V/ueciRjPkik309bYY9SjD9uf3iX/7UKCeCFNT9TwNLt1at5lBMg/9n5NMW2hpH41cdolYwPOd+fGpKu/c0bNR/Xud2cxktr7JQ8LWpj4937USl+3pdl9oeFQbgWvD4EGvNuh3lE9k77YRE8U=,iv:dOtxHUgmCs6U4yn9CLB0/1wmYbo5Su2RaKhEubMD93E=,tag:IgcnIR58tj/HiVg939j+pQ==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUzlIM3FrM0pkTGJab1A1
            dGI3WTFBUnZWVG5TcHIzbExhektmYXRFMlE4CjdFZE1KcmpETytxMFpEWlVrbkRB
            SzhNaDk1TVhxbENTdUNMZG1HZDhDOFkKLS0tIDhaN3RhemdCUkVqWWNlK3plK1U5
            OEg4aTJTb3JiLzNYTHBJTXM5dXpjN2cKdU5JWiqY6GhNWayzF4pInhwWZzwWQTje
            tg094W3txTebYDT3KXFqgdip8avfY1oknQj0ilJLh86TO+uAe9wQUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T23:31:21Z"
    mac: ENC[AES256_GCM,data:OFj8CfHTrhaqyvpHreEvAf8whYzG/+Kf8z4svtmVF66ucvsdrFpl4/KhkiiBuBe/Uau9Y1xjFZoJbCriHpyaWILO1SBhByGvC2Ep5B0UYrLAzFqXhbeZntBC7dqdLd9L3TsZct1CtBg/KF0uf1TOasRpRpJqc4GCIMuiMt31XMw=,iv:iv7hqh0cYRVNJjgwUppWhZ1yIgpMFKZcGoEScjowh5o=,tag:y0Rp2pSwz4L4/aTWhf5WqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
