apiVersion: v1
kind: Secret
metadata:
    name: ntfy-server-secret
    namespace: ntfy
type: Opaque
stringData:
    server.yaml: ENC[AES256_GCM,data:RGymIouYRMo5pwuKToVvXUqh5MPVFYYPO8wI3kOQ6MZPCtY/tkmmEj7iDiUmqHCMl7jHkBAfSXZZzA8G50kNnINEdvEQr6LBAmAnNorUb9nG+ZnRdwhKnQ4opROMLJqjN57fXIg9/GxhFdB2NRqhLktAUVfnF3SiqWDvrvGnq7wOUf5y+U4tFXjkg3V98KTNB+gLBUi/QDEAY3BmYTcxW4kQW68C82i7gxLUr4m1Jlt2IR8ggR/0lMrfFhkjKS4f4g0lSw72t2gzu2CneAVCJWP6ZIMPuIN6wFXFxOzGfOcrs0LebDvKunp9b4XIdr4YCymMgzz3V8vOwW716yFLstCX8pnbot58WAEuKvlyIB5Z5qCc8ZQ90hPtsaohNxFSKnk3lu5wCM69GfMRT8MwAuIPKaWRrdQQBYE43WnCsQ1JVm388QQz3VNlc0u4stuN3zlcywO4qWbZO9XDa/GJ23l+e7kJfKisX1I5vhDXIE2pceFlDFsmpgaoslrQuL19RCHZ77q7QRlFEfKjc6nmsM5UFnXIID/WNu7MxalekNTaAZv2tu/kwE5yYFWcjOLBUy732I1BBDq398qx2D1wG9wl9ipia8jLRUXT3WTrG/U7mNADSNdvdvXRKIiPjsjPtbHdBE88aaJfV25A+qZCeRlEDtG0RN6helKJy73sI1Mi+IF59iktA/SDf07o2QTXpK//VfAljP6f,iv:Q5kvUCkqhaGV0K3tYJimeHlwhfxYR6dSfH0tnxmTtTY=,tag:TicEvmioiuVLaoesIF5h/A==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUzlIM3FrM0pkTGJab1A1
            dGI3WTFBUnZWVG5TcHIzbExhektmYXRFMlE4CjdFZE1KcmpETytxMFpEWlVrbkRB
            SzhNaDk1TVhxbENTdUNMZG1HZDhDOFkKLS0tIDhaN3RhemdCUkVqWWNlK3plK1U5
            OEg4aTJTb3JiLzNYTHBJTXM5dXpjN2cKdU5JWiqY6GhNWayzF4pInhwWZzwWQTje
            tg094W3txTebYDT3KXFqgdip8avfY1oknQj0ilJLh86TO+uAe9wQUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T22:56:30Z"
    mac: ENC[AES256_GCM,data:Bh5W3n1k5e9VlJdYJYDyrjtsPbh4kylpeDSt8mWhYj3riISUwLNSnkRs3MWbLDt8jTXhcb+zcspJd88vtIsZ8vplCp6t2y9i9LuMaffcBfK3/J3djs+5EQXkR3Q63rAa3BkMpf2+LUHVYfdcMudzrBXcQcMovwuAHwVsAr22L4A=,iv:cEE3mmoKAP3iy6yKCazc65wpsNN5VfFCJAwjPywA3Ss=,tag:AUtGuf62jBPEgLW/q6QoNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
