apiVersion: v1
kind: Secret
metadata:
    name: ntfy-server-secret
    namespace: ntfy
type: Opaque
stringData:
    server.yml: ENC[AES256_GCM,data:T+dNlIxx6jvDlw4o9gx75NKl9/3IpE9xtp+lo4vugaB/vq+Vc59ZuVfKJgeMuzUkqCOWv+G7bUEbLEDWtZx9g6q72Z+eLTdDLcJnkK05UnYOtz5kp+rz+/ErUDG1lAivE2wuMMugJBfr1gaAR/iFyDTQuXiwwIfR1o6gITGhTBSIE7iew9xECqcYzrkJZDyceqG4AJ+lsySTN3GicZNTIZ1kOtVuZaCAVtNYmtk3AwIIzh7N92aqW2aKRTEDRxf21Ew7QLwY+HvFfecv0Jd/ofc80N+eDR1CNMMaPkXbSk7EtVugvxKgQLzv1f2J9ahO1FYtPS5ZoTBytWu0dFXV0i8dSY+ce7MtRipqoLemr41lm4VQW0XoG7RZqsMc4CAyuG7mKbmJhwFERYpBJt93s5S8Y/iWYScMTfTXRba05s2WRy2I1cRfFRscWLZcyXTENAXqq1S6DoYkbUHFYi6Xjx8Lo58iEXgNdRFKDIPJvfVXLWouJPyG5pUzrxn+00XTr7r0AgvP9MFo0pGEePLfEBi1w1fi5a/4Rds+26uBTYsIvSUoWHc8EAvtwdVxu9DryluH9tk2VHvIv/FpW64dDdeMVK/lnM+pwnrARrnP4iTQb1yFdbAvoz+zOCJ3IVG2UD+ZsUoVMF6ZXA/g/Hd+IHFfwQOTawK+n8APR9J2ECRrEtuCcrbjMP7Tpy4wkxk/sM71C/SVn47PrmQ=,iv:jafxoyqk0583LJKj8DQvMSNVGXL1VpR+4qzoyj/4PDY=,tag:E1w4gJXJhhJ06FMjL00r8w==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUzlIM3FrM0pkTGJab1A1
            dGI3WTFBUnZWVG5TcHIzbExhektmYXRFMlE4CjdFZE1KcmpETytxMFpEWlVrbkRB
            SzhNaDk1TVhxbENTdUNMZG1HZDhDOFkKLS0tIDhaN3RhemdCUkVqWWNlK3plK1U5
            OEg4aTJTb3JiLzNYTHBJTXM5dXpjN2cKdU5JWiqY6GhNWayzF4pInhwWZzwWQTje
            tg094W3txTebYDT3KXFqgdip8avfY1oknQj0ilJLh86TO+uAe9wQUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T23:41:29Z"
    mac: ENC[AES256_GCM,data:X/vDeJHMVjMQdYtnrimFBNkI0vruXXn4CK+ChUSbiQcKyyp9MMsTfqClUcFVHEqLn8Pk4byye9nYPd4trYQczrU76EqUTa2IIXJHKOLNhtUUwya0RF0R+CH0VRwFZxoEKAr2syB9IaBVcyO+H0ucPaxa7yGmuTKHxRs1oGIPrUg=,iv:99jUOUKkENu4KL6twnRHgO+RUar3mXFt0tIVthdZpPM=,tag:4cGZkl9/plqN0udjKWyh5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
