apiVersion: v1
kind: Secret
metadata:
    name: ygg-gateway-secret
    namespace: ygg-gateway
type: Opaque
stringData:
    REMOTE_SOCKS: ENC[AES256_GCM,data:tTFvSfc8LvVMUh4joG500qQTy/lnQtTCx57uZE7+xixsuCuwtqG6Zkm8QvMXEQEGqT9Z7XMEi2NRevAkHxOJJGthlXQZkU8QYm0+2wHTYrJdVnwgeRnPaBu2JVRJktVg,iv:F1P9bsaPJCXKmhwJ0mTb3QcCjXpNVhNhEph/XPHMtT8=,tag:hIrqNqa3rAycxIACX44+1A==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNG5MNUIxbU9BNTNHdW10
            aFo1Y0t2QTY3YkFYQnUzVEFUdmdjMVZkR0FJClBjN2tEOUZrWU5tbDNOTnppVHNq
            dmtzRGNBajJkVDRuMnEyUUlpYlk4Y2cKLS0tIFVJWXZGcUdwMDRESE8yV0lPYlVY
            N1FtR0VjQ3BnNlZCWm92UFJtS1FYQUkK392St4jN1kITzg6oW3UTZVstzK4kH9gQ
            sB0QFdnRNaQ7f++/gc4G2UG2oHd6zN6VQCyRX+c+TfZXfGZnh/mdgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T13:33:26Z"
    mac: ENC[AES256_GCM,data:hD2RFRxoaAq2GQ87kZ6zqk7PB+ooQ8t2gi1+00cMYilkNeuRSAuKtBWFjkeCfosahw04WCx5B7Xz7p2/UOk/cvrKxsBUuqmXfLs4yWj1bPLORTpR5Udo86YPaxBg4jdEvTLRm25z2f42Kp4/2uvSw6ckq4EGJs1tIcfH57Gkut4=,iv:t6IQcoiRvZ+aZT/AcV4l17BZfLEpkQvvLSMeBeSJ6r4=,tag:nb69QWRD77/jKiR0cH122w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
