apiVersion: v1
kind: Secret
metadata:
    name: ygg-gateway-secret
    namespace: backup-critical-data
type: Opaque
stringData:
    REMOTE_SOCKS: ENC[AES256_GCM,data:tTFvSfc8LvVMUh4joG500qQTy/lnQtTCx57uZE7+xixsuCuwtqG6Zkm8QvMXEQEGqT9Z7XMEi2NRevAkHxOJJGthlXQZkU8QYm0+2wHTYrJdVnwgeRnPaBu2JVRJktVg,iv:F1P9bsaPJCXKmhwJ0mTb3QcCjXpNVhNhEph/XPHMtT8=,tag:hIrqNqa3rAycxIACX44+1A==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNG5MNUIxbU9BNTNHdW10
            aFo1Y0t2QTY3YkFYQnUzVEFUdmdjMVZkR0FJClBjN2tEOUZrWU5tbDNOTnppVHNq
            dmtzRGNBajJkVDRuMnEyUUlpYlk4Y2cKLS0tIFVJWXZGcUdwMDRESE8yV0lPYlVY
            N1FtR0VjQ3BnNlZCWm92UFJtS1FYQUkK392St4jN1kITzg6oW3UTZVstzK4kH9gQ
            sB0QFdnRNaQ7f++/gc4G2UG2oHd6zN6VQCyRX+c+TfZXfGZnh/mdgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T13:25:20Z"
    mac: ENC[AES256_GCM,data:fKXwXH1vNjpuUTqMgRxSVVWI2DH1QF2wHqUeWv0QXtVkARBLXIa8jdezXxNlNiyO0iFbBfhCxoqUajfEpojy5uieuvkdm1rE3qTaROwxuAVjrx+d1ApYXxbC89mC+qFbzNmrFc/Xq5v4ESVh+ZsD8DJMXwnCbsQ82yTnkCpXttg=,iv:TqQRmbIZ+giiWYgOhvbn+Mm7wnvSlEAT5P2BEyzp8L4=,tag:OMSrqTJYqgASyWeVCyovsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
