apiVersion: v1
kind: Secret
metadata:
    name: databag-secret
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:j2zuZOH8teSAEZjpRdkMzhZ89c7VoBSfNd6WPYmOTN8Unw==,iv:dCS2xUMjfeMDxFezuwukWgCIt5FbCdmP3AAHeAwxn+s=,tag:3qoqWGDCsXfgLElnwf1rLA==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMd284c3RqUVpOdGY1ZHdG
            QkptM2pyZW1LazdWRmhRRTJmblVtc1c5VDBRCmxnREdrRHIzaGwva3llWXBiNkZX
            cXBvMFhUeGN0eUFGUzB5emN3TFNKK1kKLS0tIFlnM3Y2eENjYm5XZGxyQ2QzYkZQ
            SnhYZ0tWc04vaVFtM1BnNWRZbDhaV2cK1CkFUVl/ZQAmOopbSbFBAuQW/jXDv5lP
            M3/IszSWE4Oun77SRJd2YncNDthrnOjMxmJzVuo2fCzRaujNGvA3yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T19:12:54Z"
    mac: ENC[AES256_GCM,data:tpu9nj99gFCfTX3S/+tXp4nOuHOmczanaA4hJ3q9rMJyIjTp50PiYMN3fckCmJcVmyb/nTo8lbQ7k6L3EhECjaOVC720PY/ZrJII7eLNdag9oIVlYTLNsIQHcnR53sgf61CG9zRtGCTKd8WS734kdgiYc5TNW8up/daghyoK31E=,iv:NLJxxFN08ArAnR7yaIfTB82yjgZqtLZBhGes1vCFzUc=,tag:ajyq+t2QEK1RP+GK79/nOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
