apiVersion: v1
kind: Secret
metadata:
    name: databag-secret
    namespace: databag
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:j2zuZOH8teSAEZjpRdkMzhZ89c7VoBSfNd6WPYmOTN8Unw==,iv:dCS2xUMjfeMDxFezuwukWgCIt5FbCdmP3AAHeAwxn+s=,tag:3qoqWGDCsXfgLElnwf1rLA==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMd284c3RqUVpOdGY1ZHdG
            QkptM2pyZW1LazdWRmhRRTJmblVtc1c5VDBRCmxnREdrRHIzaGwva3llWXBiNkZX
            cXBvMFhUeGN0eUFGUzB5emN3TFNKK1kKLS0tIFlnM3Y2eENjYm5XZGxyQ2QzYkZQ
            SnhYZ0tWc04vaVFtM1BnNWRZbDhaV2cK1CkFUVl/ZQAmOopbSbFBAuQW/jXDv5lP
            M3/IszSWE4Oun77SRJd2YncNDthrnOjMxmJzVuo2fCzRaujNGvA3yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T19:15:31Z"
    mac: ENC[AES256_GCM,data:uZT7EEgNSAOp2TQ2BqoVi6Dau6XTi2aYnDOLhIlzI9gUERriufNB9ZAFaWX/NvFd91wcJeuGkV92h5uipPrlZR1J/1FdKOd6G88LvoAUK9eIwimgJxMcdrb6XVRZJux9cX3H4XNPuZMPBv1l5enX7tkCJTkWYLx0dCxRvT1iRyw=,iv:+eSp+z6TcszzvROM1BY+7KHZMcIvTQjqyu4R27zNLhM=,tag:pen+CttnynUU9SlhHqsVlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
