apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haproxy-ingress
  namespace: haproxy-ingress
spec:
  releaseName: haproxy-ingress
  chart:
    spec:
      chart: haproxy-ingress
      version: "0.15.1"
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
        namespace: haproxy-ingress
  interval: 15m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Defaults: values.yaml https://github.com/haproxy-ingress/charts/blob/release-0.15/haproxy-ingress/values.yaml
  values:
    controller:
      kind: DaemonSet
      logs:
        enabled: true
      ingressClassResource:
        enabled: true
        default: true
      service:
        type: NodePort
        externalTrafficPolicy: Local
        httpPorts:
          - port: 80
            targetPort: http
            nodePort: 30080
        httpsPorts:
          - port: 443
            targetPort: https
            nodePort: 30443
      defaultBackendService: honeypot/hellpot-service
      config:
        global-config-snippet: |
          backend st_bad_ips
            stick-table type ip size 1m expire 24h store gpc0

        frontend-config-snippet: |
          http-request silent-drop if { src,table_gpc0(st_bad_ips) gt 0 }

          acl is_bad_path path -m beg /.env /.git /wp-admin /phpmyadmin
          
          http-request track-sc0 src table st_bad_ips if is_bad_path
          http-request sc-inc-gpc0(0) if is_bad_path
          
          use_backend honeypot_hellpot-service_8080 if is_bad_path      
      stats:
        enabled: true
      metrics:
        enabled: true
