apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - helm-repo.yaml
  - helm-release.yaml

configMapGenerator:
  - name: haproxy-geoip-lua
    namespace: haproxy-ingress
    files:
      - mmdb.lua
      - haproxy_mmdb.lua
    options:
      disableNameSuffixHash: true