apiVersion: v1
kind: Secret
metadata:
    name: zot-secret
    namespace: zot
type: Opaque
stringData:
    #ENC[AES256_GCM,data:vNyxlY4AwsgFv05xSRW076Pn2U+3qfTXbKI4dZc6k0Z6rIUoTV7KNptzEiwQxH3Xc3jd,iv:MwfrpYJfoJ2d1FlYyRz4gJ5rM5ORaZIwQWIJPpVTK/c=,tag:ax+nhajlm6mjbi288DTYJg==,type:comment]
    #ENC[AES256_GCM,data:7eJJdF/MOxTObZfGGLpfWpKJRaWpeYZsd+/8qKGuXT5IC2PaoubD3pxaAfJCmZN/zrXMXXbTat0m27ePBQ==,iv:8dBsZF9b2vO03ZkeRxsYV4VbRUnK5mtI2BqGmPjDa4g=,tag:TtRFCFwCwnC7sJXhO69M4g==,type:comment]
    htpasswd: ENC[AES256_GCM,data:0yvt6TDsEq1i1+iGOWzF6H3iQQxT9g6ji0bFkwNBLKvA/VW1T2GMaHVhVQZPke2Y9mtXzfuF95Tkx3zjuLUcyJjd,iv:h5qqqNow/efTHCFMQ8r3mnzFIaqQ95i4BfaYvUeJTKE=,tag:+ETYEUZnkMR8G8CHAKMUBw==,type:str]
sops:
    age:
        - recipient: age1r3mx0sh3afe32wxjzvq9u6qvfzmwlzp7uhqxravjjlnyvpz6eufq9ae0f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDL20yUGF1RFVxdUxma1pJ
            VFBXWXBWNXo5OUF0QituREtVRHRIV2RGcGlzCjRWRnB5UkMxRHJEcFBBOWJOWmdq
            U0svdldVdEh1T3lkTlZFOTlJbVp3aTQKLS0tIHV0Z2ZIUlR1SVRJLzdUMXlRUTFl
            bjNoeU9DTXptTXFhd09Hd2lJYUtIRGMKlIxre+vj23GxRcmMmBzxBtgdmjqQbR+T
            YgnIM8jCvOxLApIy5cUwqtHMIYwdiG28F03bNZGS+AnfVX9zYiC2HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T21:36:37Z"
    mac: ENC[AES256_GCM,data:GpyVIwQ00zbBBgdfjNxwcuA3bL3WXrYSqzu3eN4x4qaSbqshp/Wh+92SA/qO2le2os2A3YETc2Xe6rvBlWEECuW/wkjzl1NhvDPFSpKlns7kI8XBwdsf8xQ8SzoKaQNaebni+NRtIWQcL2ullzvv/e6AwdxftfGfFJC6KgutJ/k=,iv:00XavaEfZ+1akTOHgIyGtJ2vBjCZXaVa2/UnPT98qg0=,tag:FMCpCVQ4/57VW2hfAO9OvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
