apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: gw-external
  namespace: envoy-gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: gw-external
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gw-external
  namespace: envoy-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: gw-external
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: grafana.themiple.ru
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          group: ""
          name: letsencrypt
    
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: gw-external
  namespace: envoy-gateway
spec:
  shutdown:
    drainTimeout: "1s"
    minDrainDuration: "1s"
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
        patch:
          value:
            spec:
              type: NodePort
              ports:
                - port: 80
                  nodePort: 30080
                - port: 443
                  nodePort: 30443