apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: gw-external
  namespace: envoy-gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: gw-external
    namespace: envoy-gateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gw-external
  namespace: envoy-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: gw-external
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https-grafana
      protocol: HTTPS
      port: 443
      hostname: "grafana.themiple.ru"
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: grafana-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: grafana
    - name: https-immich
      protocol: HTTPS
      port: 443
      hostname: "immich.themiple.ru"
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: immich-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: immich
    - name: https-pocketid
      protocol: HTTPS
      port: 443
      hostname: "pocketid.themiple.ru"
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: pocketid-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: pocketid           
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: gw-external
  namespace: envoy-gateway
spec:
  shutdown:
    drainTimeout: "1s"
    minDrainDuration: "1s"
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
        patch:
          type: StrategicMerge
          value:
            spec:
              type: NodePort
              ports:
                - name: http
                  port: 80
                  protocol: TCP
                  nodePort: 30080
                - name: https
                  port: 443
                  protocol: TCP
                  nodePort: 30443
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: http-client-ip-detection
  namespace: envoy-gateway
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gw-external
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 2