apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway
spec:
  interval: 120m
  driftDetection:
    mode: enabled
  chartRef:
    kind: HelmRepository
    name: envoy-gateway
    namespace: envoy-gateway
  values:
    config:
      envoyGateway:
        extensionApis:
          enableEnvoyPatchPolicy: true