apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: network
spec:
  interval: 120m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
  values:
    config:
      envoyGateway:
        extensionApis:
          enableEnvoyPatchPolicy: true